# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache-TinyCP
version:      1.00
version_from: lib/Apache/TinyCP.pm
installdirs:  site
requires:
    Apache::Constants:             0
    Apache::FakeRequest:           0
    Cache::File:                   0
    POSIX:                         0
    Template:                      0
    Test::More:                    0
    Text::KwikiFormatish:          0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.16
